# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-03 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clonemain', '0002_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
