# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190829_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.TextField(),
        ),
    ]
